apiVersion: apps/v1
kind: Deployment
metadata:
  name: manageraccount
  labels:
    app: manageraccount-app
spec:
  selector:
    matchLabels:
      app: manageraccount-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: manageraccount-app
        tier: frontend
    spec:
      containers:
      - image: hufsie96/manageraccount
        imagePullPolicy: Always
        name: manageraccount
        env:
        - name: MYSQL_HOST
          value: mgmt-mysql
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mgmt-mysql-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mgmt-mysql-pass
              key: password
        ports:
        - containerPort: 8080
          name: manageraccount
---
apiVersion: v1
kind: Service
metadata:
  name: manageraccount
  labels:
    app: manageraccount-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: manageraccount-app
    tier: frontend
  type: LoadBalancer
