apiVersion: v1
kind: PersistentVolume
metadata:
  name: mgmtaccount-mysql-pv-volume
  namespace: library
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mgmtaccount-mysql-pv-claim
  namespace: library
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mgmtaccount-mysql
  namespace: library
  labels:
    app: mgmtaccount-app
spec:
  ports:
    - port: 3306
  selector:
    app: mgmtaccount-app
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgmtaccount-mysql
  namespace: library
  labels:
    app: mgmtaccount-app
spec:
  selector:
    matchLabels:
      app: mgmtaccount-app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mgmtaccount-app
        tier: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mgmtaccount-mysql
          args: ["--character-set-server=utf8", "--collation-server=utf8_unicode_ci"]
          env:
            - name: MYSQL_DATABASE
              value: manageraccount
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mgmtaccount-mysql-pass
                  key: rootpassword
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mgmtaccount-mysql-pass
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mgmtaccount-mysql-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mgmtaccount-mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mgmtaccount-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mgmtaccount-mysql-pv-claim
