spring:
  profiles:
    group:
      "local": "localdb,common,localms"

---
spring:
  profiles:
    group:
      "dev": "devdb,common,devms"

---
spring:
  config:
    activate:
      on-profile: "localdb"
  h2:
    console:
      enabled: true
      path: /h2/manageraccount
      settings:
        trace: true

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/manageraccount
      username: sa
      password: 1234
    platform: h2
    initialization-mode: always

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    show-sql: true
    generate-ddl: true

server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: "devdb"
  datasource:
    hikari:
      driver-class-name: "com.mysql.jdbc.Driver"
      jdbc-url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/management"
      username: sa
      password: 1234
    initialization-mode: always

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    show-sql: true
    generate-ddl: true

---
spring:
  config:
    activate:
      on-profile: "common"
  thymeleaf:
    prefix: "classpath:/templates/"
    check-template-location: true
    suffix=: ".html"
    mode: "HTML5"
    cache: false

---
spring:
  config:
    activate:
      on-profile: "localms"
kep:
  management:
    url: http://${MANAGEMENT_HOST}:8081
    host: ${MANAGEMENT_HOST}
  manageraccount:
    url: http://${MANAGERACCOUNT_HOST}:8082
    host: ${MANAGERACCOUNT_HOST}

---
spring:
  config:
    activate:
      on-profile: "devms"
kep:
  management:
    url: http://management:8080
    host: management
  manageraccount:
    url: http://manageraccount:8080
    host: manageraccount



